name: Build
on:
  push:
    branches: 
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Set up JDK Corretto 8
      uses: actions/setup-java@v3
      with:
        distribution: 'corretto'
        java-version: '8'
        architecture: x64
    - name: Maven Build
      run: mvn clean install  -D skipTests -D maven.test.skip=true
   
